name: Release Extension

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get version from manifest
        id: get_version
        run: |
          VERSION=$(jq -r .version manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create ZIP
        run: |
          # Zip the current directory contents, excluding git and hidden files
          zip -r gps-serial-bridge-v${{ env.VERSION }}.zip . -x "*.git*" ".github/*" "node_modules/*"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            gps-serial-bridge-v${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
